/**
 * Grok Analysis Motor
 * 
 * Wraps the Grok API to analyze ideas generated by Skape.
 * Grok provides powerful reasoning capabilities for idea evaluation.
 */

import { Anthropic } from '@anthropic-ai/sdk';

/**
 * GrokMotor - Analysis engine powered by Grok
 * 
 * Handles idea analysis through Grok's reasoning capabilities.
 * Input: normalized idea from Skape adapter
 * Output: structured analysis result
 */
class GrokMotor {
  constructor(apiKey) {
    if (!apiKey) {
      throw new Error('GROK_API_KEY environment variable is required');
    }
    
    this.client = new Anthropic({
      apiKey: apiKey,
      defaultHeaders: {
        'X-Model': 'grok-beta'
      }
    });
    
    this.model = 'claude-3-5-sonnet-20241022';
  }

  /**
   * Analyze an idea
   * @param {Object} idea - Normalized idea object from Skape adapter
   * @param {string} idea.id - Unique idea identifier
   * @param {string} idea.title - Idea title
   * @param {string} idea.description - Detailed description
   * @param {Array} idea.tags - Optional tags/categories
   * @returns {Promise<Object>} Analysis result
   */
  async analyze(idea) {
    if (!idea || !idea.title || !idea.description) {
      throw new Error('Invalid idea format: requires title and description');
    }

    const prompt = this.buildAnalysisPrompt(idea);

    try {
      const response = await this.client.messages.create({
        model: this.model,
        max_tokens: 1024,
        messages: [
          {
            role: 'user',
            content: prompt
          }
        ]
      });

      return this.parseAnalysisResponse(idea, response);
    } catch (error) {
      throw new Error(`Grok analysis failed: ${error.message}`);
    }
  }

  /**
   * Analyze multiple ideas in batch
   * @param {Array} ideas - Array of idea objects
   * @returns {Promise<Array>} Array of analysis results
   */
  async analyzeBatch(ideas) {
    if (!Array.isArray(ideas)) {
      throw new Error('Ideas must be an array');
    }

    return Promise.all(ideas.map(idea => this.analyze(idea)));
  }

  /**
   * Build the analysis prompt for Grok
   * @private
   */
  buildAnalysisPrompt(idea) {
    return `Analyze the following idea and provide a structured evaluation:

Title: ${idea.title}
Description: ${idea.description}
${idea.tags ? `Tags: ${idea.tags.join(', ')}` : ''}

Please provide analysis in the following format:
1. Feasibility (High/Medium/Low): Brief assessment
2. Impact (High/Medium/Low): Potential impact
3. Novelty (High/Medium/Low): How novel is this idea
4. Key Strengths: 2-3 main strengths
5. Key Challenges: 2-3 main challenges
6. Next Steps: Recommended next steps for development
7. Overall Assessment: Brief summary

Be concise but thorough.`;
  }

  /**
   * Parse Grok's response into structured analysis
   * @private
   */
  parseAnalysisResponse(idea, response) {
    const analysisText = response.content[0].text;

    return {
      ideaId: idea.id || `idea-${Date.now()}`,
      ideaTitle: idea.title,
      analysisText: analysisText,
      timestamp: new Date().toISOString(),
      model: 'grok',
      tokensUsed: {
        input: response.usage.input_tokens,
        output: response.usage.output_tokens
      }
    };
  }
}

export default GrokMotor;
